### PR TITLE
Set closure compiler language in to ECMASCRIPT5_STRICT

### PR DESCRIPTION
**Pull request by fredj**
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

### CODE REVIEW

**Comment by elemoine** [comment]
Please merge. Thanks.

**Comment by sbrunner** [comment]
Should it be done in c2cgeoportal also ?

**Comment by elemoine** [comment]
Yes, it should. I'll create a path for geoportailv3, for you to backport to c2cgeoportal. Works for you?

**Comment by sbrunner** [comment]
Yes :-)

**Comment by elemoine** [comment]
See https://github.com/Geoportail-Luxembourg/geoportailv3/pull/434.

**Pull request merged**
