### PR TITLE
Fix build from fresh clone

### PR DESCRIPTION
**Pull request by gberaudo**
Add missing jquery extern and fixed typo in Makefile.

### CODE REVIEW

**Comment by gberaudo** [comment]
Fixes #46

**Comment by elemoine** [comment]
It looks like ProjectSample still misses externs when compared to the scaffold, no?

**Comment by gberaudo** [comment]
@elemoine, I know understand `ProjectSample` is the result of the `.build/venv/bin/pcreate -s pyramid_closure ProjectSample` command. What is it for?

**Comment by elemoine** [comment]
Just have an example we can test.

**Comment by gberaudo** [comment]
It is a bit confusing to have it in the source tree. What about renaming it to` GeneratedProjectSample` or eventually removing it?

Anyway, I updated the PR with the result of the pcreate command and it is ready for merging.

**Comment by elemoine** [comment]
I don't want to remove it. It's very convenient for testing.

Please merge.

**Comment by gberaudo** [comment]
@elemoine, I tested by removing the ProjectSample, recreating it and running `git diff`.
Is it the intended way?

**Comment by elemoine** [comment]
You don't need to remove it. You can apply the template on an existing project.

**Comment by fredj** [comment]
> @elemoine, I tested by removing the ProjectSample, recreating it and running git diff.
Is it the intended way?

This is also how I refresh ProjectSample.

**Comment by gberaudo** [comment]
I tested with a modified build.json and it is not overwritten on a call to `pcreate`.
I need to remove it, or more safely remove the entire directory to get it recreated.

**Comment by elemoine** [comment]
There's an `--overwrite` option you can use.

**Pull request merged**
